//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_ModMan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS_ModMan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disabled {
            get {
                object obj = ResourceManager.GetObject("disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///	&lt;!-- Mods-out-of-Date Patch Notice --&gt;
        ///	&lt;template name=&quot;modsood_buttons&quot;&gt;
        ///		&lt;label 
        ///			align=&quot;center&quot; x=&quot;0h&quot; width=&quot;100%&quot;
        ///			valign=&quot;top&quot; y=&quot;0.2h&quot; height=&quot;1h&quot;
        ///			color=&quot;white&quot; shadow=&quot;1&quot; textalign=&quot;center&quot; textvalign=&quot;center&quot; font=&quot;dyn_9&quot; content=&quot;You should re-apply your mods before playing.&quot;
        ///		/&gt;
        ///		
        ///		&lt;instance name=&quot;button2&quot;
        ///			align=&quot;center&quot; x=&quot;-6h&quot; width=&quot;10h&quot;
        ///			valign=&quot;bottom&quot; y=&quot;-0.8h&quot; height=&quot;2.4h&quot;
        ///			label=&quot;/playanyway&quot;
        ///			onmouseover=&quot;PlaySound(&apos;/shared/sounds/ui/button_over_01.w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModsOodReminder {
            get {
                return ResourceManager.GetString("ModsOodReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///	&lt;!-- Mods-out-of-Date Patch Notice --&gt;
        ///	&lt;trigger name=&quot;modsood_check&quot; /&gt;
        ///	&lt;template name=&quot;modsood_body&quot;&gt;
        ///		&lt;panel y=&quot;0.5h&quot; width=&quot;100%&quot; float=&quot;bottom&quot; color=&quot;invisible&quot; grow=&quot;1&quot;&gt;
        ///			&lt;label fity=&quot;1&quot; fitypadding=&quot;0.8h&quot; width=&quot;-1.6h&quot; align=&quot;center&quot; font=&quot;dyn_10&quot; color=&quot;white&quot; shadow=&quot;1&quot; noclick=&quot;1&quot; wrap=&quot;1&quot; content=&quot;You have not applied your mods since the last patch. You should re-apply your mods before playing.&quot; /&gt;
        ///			&lt;panel width=&quot;-1.6h&quot; align=&quot;center&quot; height=&quot;3.2h&quot; color=&quot;invisible&quot; noclick=&quot;1&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModsOodReminderFE2 {
            get {
                return ResourceManager.GetString("ModsOodReminderFE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updating {
            get {
                object obj = ResourceManager.GetObject("updating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
